/* Generated by scripts/build-characters.mjs — do not edit by hand. */

export type CharacterAsset = {
  /** Intrinsic size of the largest export, for aspect ratio. */
  w: number;
  h: number;
  /** Named points as [x, y] fractions of the image. */
  anchors: Record<string, [number, number]>;
};

export const characterAssets = {
  "boy-tap": {
    "w": 959,
    "h": 1199,
    "anchors": {
      "fingertip": [
        0.0323,
        0.8324
      ],
      "pivot": [
        0.1449,
        0.6022
      ]
    }
  },
  "girl-press": {
    "w": 1232,
    "h": 1059,
    "anchors": {
      "fingertip": [
        0.349,
        0.8045
      ],
      "buttonTopLeft": [
        0.0357,
        0.7592
      ],
      "buttonBottomRight": [
        0.8312,
        1.0217
      ]
    }
  },
  "boy-sit": {
    "w": 836,
    "h": 1258,
    "anchors": {
      "seat": [
        -0.1687,
        0.6169
      ],
      "seatRight": [
        1.1292,
        0.6169
      ]
    }
  },
  "boy-present": {
    "w": 1137,
    "h": 1374,
    "anchors": {
      "palm": [
        0.8707,
        0.4658
      ],
      "cardCentre": [
        0.8004,
        0.3421
      ],
      "pointer": [
        0.5717,
        0.3362
      ]
    }
  },
  "boy-point": {
    "w": 1054,
    "h": 1354,
    "anchors": {
      "fingertip": [
        0.2182,
        0.2038
      ]
    }
  },
  "girl-peace": {
    "w": 1020,
    "h": 1533,
    "anchors": {}
  },
  "boy-coffee": {
    "w": 1001,
    "h": 1536,
    "anchors": {}
  },
  "girl-laptop": {
    "w": 1023,
    "h": 1510,
    "anchors": {}
  },
  "girl-point": {
    "w": 1137,
    "h": 1368,
    "anchors": {
      "fingertip": [
        0.9675,
        0.6206
      ]
    }
  },
  "girl-think": {
    "w": 1129,
    "h": 1374,
    "anchors": {}
  },
  "boy-code": {
    "w": 1145,
    "h": 1352,
    "anchors": {}
  },
  "boy-sleep": {
    "w": 1536,
    "h": 959,
    "anchors": {}
  }
} as const satisfies Record<string, CharacterAsset>;

export const CHARACTER_WIDTHS = [960,520] as const;
