// Generated by scripts/build-room-video.mjs — do not edit by hand.

/** Corners of the room that have a camera move and a resting frame. */
export const CORNERS = [{"id":"desk","seconds":1},{"id":"shelf","seconds":0.95}] as const;
export type CornerId = 'room' | (typeof CORNERS)[number]['id'];
